/**
 * @fileoverview Maps theme tokens onto Naive UI component variables.
 *
 * Naive UI resolves colors in JavaScript, so it receives literal values rather
 * than CSS custom properties. Every override here exists to make library
 * controls read as part of the same material as the custom surfaces.
 */
import type { GlobalThemeOverrides } from 'naive-ui';
import type { ThemeTokens } from './palette';

export const FONT_FAMILY =
  "'Geist Variable', -apple-system, BlinkMacSystemFont, 'Segoe UI Variable', 'Segoe UI', 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei UI', 'Microsoft YaHei', 'Noto Sans CJK SC', sans-serif";

export const FONT_FAMILY_MONO =
  "'Geist Mono Variable', ui-monospace, 'SF Mono', Menlo, Consolas, 'Liberation Mono', monospace";

export function buildNaiveOverrides(tokens: ThemeTokens): GlobalThemeOverrides {
  const focusRing = `0 0 0 3px ${tokens.glow}`;
  const raisedShadow = tokens.dark
    ? `0 0 0 1px ${tokens.hairline}, 0 12px 32px rgba(0, 0, 0, 0.45)`
    : `0 0 0 1px ${tokens.hairline}, 0 12px 32px rgba(24, 12, 48, 0.12)`;
  const overlayShadow = tokens.dark
    ? `0 0 0 1px ${tokens.border}, 0 28px 72px rgba(0, 0, 0, 0.6)`
    : `0 0 0 1px ${tokens.hairline}, 0 28px 72px rgba(24, 12, 48, 0.22)`;
  const field = {
    color: tokens.raised,
    colorFocus: tokens.raised,
    textColor: tokens.text,
    placeholderColor: tokens.textFaint,
    border: `1px solid ${tokens.border}`,
    borderHover: `1px solid ${tokens.borderStrong}`,
    borderFocus: `1px solid ${tokens.accent}`,
    boxShadowFocus: focusRing,
    caretColor: tokens.accent,
  };
  return {
    common: {
      fontFamily: FONT_FAMILY,
      fontFamilyMono: FONT_FAMILY_MONO,
      fontSize: '13px',
      fontSizeTiny: '11px',
      fontSizeSmall: '12px',
      fontSizeMedium: '13px',
      fontSizeLarge: '14px',
      fontSizeHuge: '15px',
      fontWeight: '450',
      fontWeightStrong: '600',
      lineHeight: '1.5',
      heightTiny: '24px',
      heightSmall: '30px',
      heightMedium: '34px',
      heightLarge: '40px',
      borderRadius: '9px',
      borderRadiusSmall: '7px',
      primaryColor: tokens.accent,
      primaryColorHover: tokens.accentStrong,
      primaryColorPressed: tokens.accentStrong,
      primaryColorSuppl: tokens.accentBright,
      infoColor: tokens.info,
      infoColorHover: tokens.info,
      infoColorPressed: tokens.info,
      infoColorSuppl: tokens.info,
      successColor: tokens.success,
      successColorHover: tokens.success,
      successColorPressed: tokens.success,
      successColorSuppl: tokens.success,
      warningColor: tokens.warning,
      warningColorHover: tokens.warning,
      warningColorPressed: tokens.warning,
      warningColorSuppl: tokens.warning,
      errorColor: tokens.danger,
      errorColorHover: tokens.danger,
      errorColorPressed: tokens.danger,
      errorColorSuppl: tokens.danger,
      textColorBase: tokens.text,
      textColor1: tokens.text,
      textColor2: tokens.text,
      textColor3: tokens.textMuted,
      textColorDisabled: tokens.textFaint,
      placeholderColor: tokens.textFaint,
      iconColor: tokens.textMuted,
      iconColorHover: tokens.text,
      iconColorPressed: tokens.text,
      closeIconColor: tokens.textMuted,
      closeIconColorHover: tokens.text,
      closeColorHover: tokens.hover,
      closeColorPressed: tokens.pressed,
      bodyColor: tokens.canvas,
      cardColor: tokens.raised,
      modalColor: tokens.overlay,
      popoverColor: tokens.overlay,
      tableColor: tokens.raised,
      tableHeaderColor: tokens.fill,
      inputColor: tokens.raised,
      actionColor: tokens.fill,
      tagColor: tokens.fill,
      codeColor: tokens.fill,
      hoverColor: tokens.hover,
      pressedColor: tokens.pressed,
      borderColor: tokens.border,
      dividerColor: tokens.hairline,
      scrollbarColor: tokens.scrollbar,
      scrollbarColorHover: tokens.scrollbar,
      boxShadow1: raisedShadow,
      boxShadow2: raisedShadow,
      boxShadow3: overlayShadow,
      opacityDisabled: '0.45',
      cubicBezierEaseInOut: 'cubic-bezier(0.2, 0, 0, 1)',
      cubicBezierEaseOut: 'cubic-bezier(0.2, 0, 0, 1)',
      cubicBezierEaseIn: 'cubic-bezier(0.4, 0, 1, 1)',
    },
    Button: {
      fontWeight: '500',
      border: `1px solid ${tokens.border}`,
      borderHover: `1px solid ${tokens.borderStrong}`,
      borderPressed: `1px solid ${tokens.borderStrong}`,
      borderFocus: `1px solid ${tokens.borderStrong}`,
      colorHover: tokens.hover,
      colorPressed: tokens.pressed,
      textColorPrimary: tokens.onAccent,
      textColorHoverPrimary: tokens.onAccent,
      textColorPressedPrimary: tokens.onAccent,
      textColorFocusPrimary: tokens.onAccent,
      textColorError: tokens.dark ? tokens.onInverse : '#ffffff',
      textColorHoverError: tokens.dark ? tokens.onInverse : '#ffffff',
      textColorPressedError: tokens.dark ? tokens.onInverse : '#ffffff',
      textColorFocusError: tokens.dark ? tokens.onInverse : '#ffffff',
      colorQuaternaryHover: tokens.hover,
      colorQuaternaryPressed: tokens.pressed,
      colorSecondary: tokens.fill,
      colorSecondaryHover: tokens.fillStrong,
      colorSecondaryPressed: tokens.fillStrong,
      colorTertiary: tokens.fill,
      colorTertiaryHover: tokens.fillStrong,
      colorTertiaryPressed: tokens.fillStrong,
    },
    Input: field,
    InputNumber: {
      peers: {
        Input: field,
        Button: { textColor: tokens.textMuted, textColorHover: tokens.text },
      },
    },
    Select: {
      peers: {
        InternalSelection: {
          ...field,
          borderActive: `1px solid ${tokens.accent}`,
          boxShadowActive: focusRing,
          arrowColor: tokens.textMuted,
        },
        InternalSelectMenu: {
          color: tokens.overlay,
          borderRadius: '11px',
          optionTextColorActive: tokens.text,
          optionTextColorPressed: tokens.text,
          optionCheckColor: tokens.accent,
          optionColorActive: tokens.selected,
          optionColorActivePending: tokens.selected,
          optionColorPending: tokens.hover,
          optionPaddingMedium: '0 10px',
        },
      },
    },
    Dropdown: {
      color: tokens.overlay,
      borderRadius: '11px',
      optionColorHover: tokens.hover,
      optionColorActive: tokens.selected,
      optionTextColorHover: tokens.text,
      optionIconSuffixWidthMedium: '0',
      optionHeightMedium: '32px',
      padding: '6px',
      optionPrefixWidthMedium: '30px',
      optionIconSizeMedium: '16px',
    },
    Popover: {
      color: tokens.overlay,
      borderRadius: '13px',
      padding: '14px 16px',
      boxShadow: raisedShadow,
    },
    Tooltip: {
      color: tokens.inverse,
      textColor: tokens.onInverse,
      borderRadius: '8px',
      padding: '6px 10px',
      boxShadow: 'none',
    },
    Card: {
      color: tokens.raised,
      textColor: tokens.text,
      titleTextColor: tokens.text,
      titleFontSizeMedium: '18px',
      titleFontWeight: '600',
      borderColor: tokens.hairline,
      borderRadius: '16px',
      boxShadow: overlayShadow,
    },
    Modal: {
      color: tokens.overlay,
      boxShadow: overlayShadow,
    },
    Dialog: {
      color: tokens.overlay,
      textColor: tokens.text,
      titleTextColor: tokens.text,
      titleFontSize: '17px',
      borderRadius: '16px',
      padding: '22px 24px 20px',
      iconSize: '24px',
      closeIconColor: tokens.textMuted,
      closeIconColorHover: tokens.text,
      closeColorHover: tokens.hover,
      actionSpace: '10px',
      contentMargin: '12px 0 20px',
    },
    Drawer: {
      color: tokens.raised,
      textColor: tokens.text,
      titleTextColor: tokens.text,
    },
    Message: {
      color: tokens.overlay,
      colorInfo: tokens.overlay,
      colorSuccess: tokens.overlay,
      colorWarning: tokens.overlay,
      colorError: tokens.overlay,
      colorLoading: tokens.overlay,
      textColor: tokens.text,
      textColorInfo: tokens.text,
      textColorSuccess: tokens.text,
      textColorWarning: tokens.text,
      textColorError: tokens.text,
      textColorLoading: tokens.text,
      iconColorInfo: tokens.info,
      iconColorSuccess: tokens.success,
      iconColorWarning: tokens.warning,
      iconColorError: tokens.danger,
      iconColorLoading: tokens.accent,
      closeIconColor: tokens.textMuted,
      closeIconColorHover: tokens.text,
      borderRadius: '12px',
      boxShadow: raisedShadow,
      padding: '10px 14px',
    },
    Switch: {
      railColor: tokens.fillStrong,
      railColorActive: tokens.accent,
      buttonColor: '#ffffff',
      boxShadowFocus: focusRing,
    },
    Checkbox: {
      color: tokens.raised,
      colorChecked: tokens.accent,
      border: `1px solid ${tokens.borderStrong}`,
      borderChecked: `1px solid ${tokens.accent}`,
      borderFocus: `1px solid ${tokens.accent}`,
      boxShadowFocus: focusRing,
      checkMarkColor: tokens.onAccent,
      borderRadius: '5px',
    },
    Radio: {
      color: tokens.raised,
      dotColorActive: tokens.accent,
      boxShadow: `inset 0 0 0 1px ${tokens.borderStrong}`,
      boxShadowActive: `inset 0 0 0 1px ${tokens.accent}`,
      boxShadowFocus: `inset 0 0 0 1px ${tokens.accent}, ${focusRing}`,
      buttonColor: tokens.raised,
      buttonColorActive: tokens.accentSoft,
      buttonTextColor: tokens.textMuted,
      buttonTextColorHover: tokens.text,
      buttonTextColorActive: tokens.accentText,
      buttonBorderColor: tokens.border,
      buttonBorderColorActive: tokens.accent,
      buttonBorderColorHover: tokens.borderStrong,
      buttonBoxShadowFocus: focusRing,
      buttonBoxShadow: 'none',
      buttonBorderRadius: '9px',
      fontSizeMedium: '13px',
    },
    Tabs: {
      tabTextColorLine: tokens.textMuted,
      tabTextColorActiveLine: tokens.text,
      tabTextColorHoverLine: tokens.text,
      tabTextColorBar: tokens.textMuted,
      tabTextColorActiveBar: tokens.text,
      tabTextColorHoverBar: tokens.text,
      tabFontWeightActive: '600',
      barColor: tokens.accent,
      tabGapMediumLine: '24px',
      tabGapSmallLine: '20px',
      tabPaddingMediumLine: '8px 0 10px',
      tabPaddingSmallLine: '6px 0 8px',
      panePaddingMedium: '16px 0 0',
      panePaddingSmall: '12px 0 0',
      colorSegment: tokens.fill,
      tabColorSegment: tokens.raised,
      tabTextColorSegment: tokens.textMuted,
      tabTextColorActiveSegment: tokens.text,
      tabTextColorHoverSegment: tokens.text,
      tabPaddingMediumSegment: '5px 14px',
      tabPaddingSmallSegment: '4px 12px',
      tabBorderRadius: '7px',
      segmentBorderRadius: '9px',
      tabFontWeightActiveSegment: '600',
    },
    Tag: {
      color: tokens.fill,
      textColor: tokens.textMuted,
      borderRadius: '999px',
      textColorCheckable: tokens.textMuted,
      textColorHoverCheckable: tokens.text,
      textColorChecked: tokens.onAccent,
      colorChecked: tokens.accent,
      colorCheckedHover: tokens.accentStrong,
      colorCheckedPressed: tokens.accentStrong,
    },
    DataTable: {
      borderRadius: '12px',
      thColor: tokens.fill,
      thTextColor: tokens.textMuted,
      thFontWeight: '500',
      tdColor: tokens.raised,
      tdColorHover: tokens.hover,
      tdColorStriped: tokens.canvas,
      borderColor: tokens.hairline,
      thPaddingSmall: '8px 12px',
      tdPaddingSmall: '9px 12px',
    },
    Pagination: {
      itemColorActive: tokens.accentSoft,
      itemTextColorActive: tokens.accentText,
      itemBorderActive: `1px solid ${tokens.accent}`,
      itemBorder: `1px solid transparent`,
      itemColorHover: tokens.hover,
      itemBorderRadius: '7px',
    },
    Progress: {
      fillColor: tokens.accent,
      railColor: tokens.fillStrong,
      railHeight: '6px',
    },
    Spin: { color: tokens.accent },
    Alert: {
      borderRadius: '11px',
      color: tokens.fill,
      colorInfo: tokens.infoSoft,
      colorSuccess: tokens.successSoft,
      colorWarning: tokens.warningSoft,
      colorError: tokens.dangerSoft,
      border: `1px solid ${tokens.hairline}`,
      borderInfo: `1px solid transparent`,
      borderSuccess: `1px solid transparent`,
      borderWarning: `1px solid transparent`,
      borderError: `1px solid transparent`,
      contentTextColor: tokens.text,
      contentTextColorInfo: tokens.text,
      contentTextColorSuccess: tokens.text,
      contentTextColorWarning: tokens.text,
      contentTextColorError: tokens.text,
      iconColorInfo: tokens.info,
      iconColorSuccess: tokens.success,
      iconColorWarning: tokens.warning,
      iconColorError: tokens.danger,
    },
    Collapse: {
      titleFontWeight: '500',
      dividerColor: tokens.hairline,
      arrowColor: tokens.textMuted,
    },
    Form: {
      labelTextColor: tokens.text,
      labelFontWeight: '500',
      labelFontSizeTopMedium: '13px',
      labelFontSizeLeftMedium: '13px',
      feedbackFontSizeMedium: '12px',
    },
    Divider: { color: tokens.hairline },
    Empty: {
      textColor: tokens.textMuted,
      iconColor: tokens.textFaint,
    },
    Descriptions: {
      thColor: tokens.fill,
      tdTextColor: tokens.text,
      thTextColor: tokens.textMuted,
      borderColor: tokens.hairline,
      borderRadius: '11px',
    },
    ColorPicker: {
      color: tokens.raised,
      border: `1px solid ${tokens.border}`,
      borderRadius: '9px',
      panelColor: tokens.overlay,
    },
    DynamicTags: {
      peers: {
        Tag: { borderRadius: '7px' },
      },
    },
  };
}
